import Head from './Head'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-24 my-12 bg-gray-800'>
        {children}
      </body>
    </html>
  )
}
