import './globals.css'

export const metadata = {
  title: 'Movie Viewer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-24 my-12 bg-gray-900'>
        {children}
      </body>
    </html>
  )
}
